---
# copyright Utrecht University

# Zabbix agent rpm location and checksum
zabbix_agent:
  package: zabbix-agent2-7.4.5
  url: https://repo.zabbix.com/zabbix/7.4/stable/rhel/9/x86_64
  filename: zabbix-agent2-7.4.5-release2.el9.x86_64.rpm
  checksum: sha256:8bb9b0590fb16a53bf43927f30cdce424b8c56182e55943bfffbf52d7aa12053
  rpm_key_loc: https://repo.zabbix.com/RPM-GPG-KEY-ZABBIX-B5333005
