---
# copyright Utrecht University

# Zabbix agent deb location and checksum
zabbix_agent:
  package: zabbix-agent2
  package_version: 7.4.5
  url: https://repo.zabbix.com/zabbix/7.4/stable/ubuntu/pool/main/z/zabbix
  filename: zabbix-agent2_7.4.5-2%2Bubuntu24.04_amd64.deb
  checksum: sha256:4b98f2d499b06a5d9a1d1960730209e1b394acd552eb2e4b8699df3232b7ee8f
