---
name: "Build Solr image and push it to registry"

on:
  push:
    branches:
      - 'master'
    paths:
      - '.github/workflows/build-push-image-solr.yml'
      - 'docker/images/solr/**'

jobs:
  push-image:
    if: github.repository == 'utrechtuniversity/epos-msl'
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: write
    steps:
    - name: Extract branch name
      shell: bash
      run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
      id: extract_branch

    - name: Check out EPOS-MSL catalog repository
      uses: actions/checkout@v6
      with:
        path: epos-msl
        repository: UtrechtUniversity/epos-msl
        ref: ${{ steps.extract_branch.outputs.branch }}

    - name: Authenticate to the container registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v6
      with:
        context: epos-msl/docker/images/solr
        file: epos-msl/docker/images/solr/Dockerfile
        push: true
        tags: ghcr.io/utrechtuniversity/epos-msl-cat-solr:latest
